# Generated by Django 4.2.4 on 2023-08-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilemodel',
        ),
    ]
