# Generated by Django 4.2.4 on 2023-09-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0004_adddetailsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('expir', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
