# Generated by Django 4.2.4 on 2023-09-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0005_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('dishname', models.CharField(max_length=30)),
                ('img', models.FileField(upload_to='eat_app/static')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
