# Generated by Django 4.2.4 on 2023-09-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0007_remove_cartmodel_dishname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartmodel',
            old_name='img',
            new_name='card',
        ),
    ]
