# Generated by Django 4.2.4 on 2023-09-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0009_delete_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pid', models.IntegerField()),
                ('card', models.FileField(upload_to='eat_app/static')),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField()),
            ],
        ),
    ]
