# Generated by Django 4.2.4 on 2023-09-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0010_wishmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='expir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='wishmodel',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
