# Generated by Django 4.2.4 on 2023-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0011_alter_paymentmodel_expir_alter_wishmodel_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishmodel',
            old_name='pid',
            new_name='num',
        ),
    ]
