# Generated by Django 4.2.4 on 2023-09-09 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0012_rename_pid_wishmodel_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishmodel',
            old_name='num',
            new_name='no_per',
        ),
    ]
