# Generated by Django 4.2.4 on 2023-09-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0013_rename_num_wishmodel_no_per'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('no_per', models.IntegerField()),
                ('dishname', models.CharField(max_length=30)),
                ('card', models.FileField(upload_to='eat_app/static')),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='wishmodel',
            name='dishname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
