# Generated by Django 4.2.4 on 2023-09-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0015_wishlistmodel_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistmodel',
            old_name='no_per',
            new_name='quantity',
        ),
    ]
