# Generated by Django 4.2.4 on 2023-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0016_rename_no_per_wishlistmodel_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('card', models.FileField(upload_to='')),
            ],
        ),
    ]
