# Generated by Django 4.2.4 on 2023-09-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0019_cartmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmodel',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
