# Generated by Django 4.2.4 on 2023-09-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0021_remove_wishmodel_card_remove_wishmodel_dishname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('card', models.FileField(upload_to='eat_app/static')),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='card',
            field=models.FileField(upload_to='eat_app/static'),
        ),
    ]
