# Generated by Django 4.2.4 on 2023-09-24 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0028_gravymodel_delete_wishlistmodel_delete_wishmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gravymodel',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='gravymodel',
            old_name='card',
            new_name='im',
        ),
        migrations.RenameField(
            model_name='gravymodel',
            old_name='price',
            new_name='pri',
        ),
    ]
