# Generated by Django 4.2.4 on 2023-09-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0030_delete_gravymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='grav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravyname', models.CharField(max_length=30)),
                ('pri', models.IntegerField()),
                ('des', models.CharField(max_length=50)),
                ('im', models.FileField(upload_to='eat_app/static')),
            ],
        ),
    ]
