# Generated by Django 4.2.4 on 2023-09-26 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0031_grav'),
    ]

    operations = [
        migrations.CreateModel(
            name='rice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ricename', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='eat_app/static')),
            ],
        ),
    ]
