# Generated by Django 4.2.4 on 2023-09-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0032_rice'),
    ]

    operations = [
        migrations.CreateModel(
            name='bfmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfname', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('img', models.FileField(upload_to='eat_app/static')),
            ],
        ),
    ]
