# Generated by Django 4.2.4 on 2023-09-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_app', '0034_icemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilmodel',
            name='date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
